# Generated by Django 3.2.6 on 2021-08-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_blogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='pstdate',
            new_name='postdate',
        ),
    ]
